### ISSUE TITLE
New lines are not shown correctly

### ISSUE THREAD

**Issue by olgagro** [egde/retro#22]
I can go to a new line in the same window, however, in the view mode, all is displayed in one line.

![image](https://user-images.githubusercontent.com/48212710/60089613-26bb7a80-9741-11e9-918b-35288b2530a2.png)

**Comment by egde** [comment]
Good - some CSS fixed this issue 🥇

**Comment by egde** [comment]
Just pushed the changes to Prod!

**Comment by olgagro** [comment]
looks good, thank you! :)
