### ISSUE TITLE
Boards naming

### ISSUE THREAD

**Issue by olgagro** [egde/retro#23]
"Good-bad..." board is written in capital letters, although everything else in normal letter. Would be great, to change this "Good-bad" name.

![image](https://user-images.githubusercontent.com/48212710/60089765-713cf700-9741-11e9-8c6f-4dcbee395286.png)

**Comment by egde** [comment]
Yes - this can be made nicer!

**Comment by egde** [comment]
@olgagro  would you like to try? It's live at retro.kazkazi.de now

**Comment by olgagro** [comment]
Cool, it works :)
