### ISSUE TITLE
Update the link sent to customers

### ISSUE THREAD

**Issue by olgagro** [egde/retro#24]
The link sent to users needs to be updated:
"boards" instead of "boardsboard" 
Example:
http://retro.kazkazi.de/#/boardsboard/37964

**Comment by egde** [comment]
Oh dear -  there I was a bit unconcentrated. I am fixing this!

**Comment by egde** [comment]
@olgagro  would you like to try? It's live at retro.kazkazi.de now

**Comment by olgagro** [comment]
Cool, it works :)
