### ISSUE TITLE
Phone web browser: not able to add text

### ISSUE THREAD

**Issue by olgagro** [egde/retro#26]
When using web browser (Chrome) on my phone, I  am able to create new issues, but I am not able to put text into it.  (See screenshot attached).
Would be useful, if people can also use the web interface from their phones.
![web](https://user-images.githubusercontent.com/48212710/60159873-642d1000-97f4-11e9-8ba9-3e859f2abc91.jpg)

**Comment by egde** [comment]
Thanks for finding this issue!

I have adapted the UI a bit now. Instead of enabling the edit mode by moving the mouse over the field, a click is now required. This way it'll work with a touch screen too.

**Comment by egde** [comment]
Just pushed the changes to Prod!

**Comment by olgagro** [comment]
looks good, thank you! :)
But now the entries appear in the down part - very difficult to find them.
